"""delete is_active

Revision ID: 08256e9d589f
Revises: 137ad573af2b
Create Date: 2025-03-15 12:59:27.073093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08256e9d589f'
down_revision: Union[str, None] = '137ad573af2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_guest', sa.Boolean(), nullable=False))
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'is_guest')
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
