"""add columns user_id

Revision ID: 0b37660060e7
Revises: 08256e9d589f
Create Date: 2025-03-15 18:02:52.491994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b37660060e7'
down_revision: Union[str, None] = '08256e9d589f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'exercises', 'users', ['user_id'], ['id'])
    op.add_column('muscle_groups', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'muscle_groups', 'users', ['user_id'], ['id'])
    op.add_column('sets', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'sets', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sets', type_='foreignkey')
    op.drop_column('sets', 'user_id')
    op.drop_constraint(None, 'muscle_groups', type_='foreignkey')
    op.drop_column('muscle_groups', 'user_id')
    op.drop_constraint(None, 'exercises', type_='foreignkey')
    op.drop_column('exercises', 'user_id')
    # ### end Alembic commands ###
