"""add new field for Set table(weight_per_exe)

Revision ID: 25eb54ae8723
Revises: 5e825978e1e6
Create Date: 2025-02-28 18:34:59.014554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25eb54ae8723'
down_revision: Union[str, None] = '5e825978e1e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sets', sa.Column('weight_per_exe', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sets', 'weight_per_exe')
    # ### end Alembic commands ###
