"""Add unique constraint for user training per day

Revision ID: 40cd318df431
Revises: 25eb54ae8723
Create Date: 2025-02-28 18:47:26.037818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40cd318df431'
down_revision: Union[str, None] = '25eb54ae8723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_training_date', 'trainings', ['user_id', 'date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_training_date', 'trainings', type_='unique')
    # ### end Alembic commands ###
