"""add onupdate for delete trainings

Revision ID: 8b676d5b4d57
Revises: 
Create Date: 2025-03-05 17:52:52.941437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b676d5b4d57'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('exercises_muscle_group_id_fkey', 'exercises', type_='foreignkey')
    op.create_foreign_key(None, 'exercises', 'muscle_groups', ['muscle_group_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('muscle_groups_training_id_fkey', 'muscle_groups', type_='foreignkey')
    op.create_foreign_key(None, 'muscle_groups', 'trainings', ['training_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('sets_exercise_id_fkey', 'sets', type_='foreignkey')
    op.create_foreign_key(None, 'sets', 'exercises', ['exercise_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sets', type_='foreignkey')
    op.create_foreign_key('sets_exercise_id_fkey', 'sets', 'exercises', ['exercise_id'], ['id'])
    op.drop_constraint(None, 'muscle_groups', type_='foreignkey')
    op.create_foreign_key('muscle_groups_training_id_fkey', 'muscle_groups', 'trainings', ['training_id'], ['id'])
    op.drop_constraint(None, 'exercises', type_='foreignkey')
    op.create_foreign_key('exercises_muscle_group_id_fkey', 'exercises', 'muscle_groups', ['muscle_group_id'], ['id'])
    # ### end Alembic commands ###
