"""Add unique constraint for user training per day

Revision ID: c082dbee9854
Revises: 7e11c33a34da
Create Date: 2025-02-28 19:17:03.052121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c082dbee9854'
down_revision: Union[str, None] = '7e11c33a34da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
